apiVersion: batch/v1
kind: Job
metadata:
  name: song-recommender-job-1736696915
  labels:
    app: song-recommender-job
spec:
  template:
    metadata:
      labels:
        app: song-recommender-job
    spec:
      restartPolicy: Never
      containers:
      - name: song-recommender-job-container
        image: gabrielurbanin/song-recommender-job:v1.0
        volumeMounts:
        - name: song-recommender-job-volume
          mountPath: /app/model
      volumes:
      - name: song-recommender-job-volume
        persistentVolumeClaim:
          claimName: project2-pvc
  backoffLimit: 4