apiVersion: batch/v1
kind: Job
metadata:
  name: song-recommender-app-job
  labels:
    app: song-recommender-app
spec:
  template:
    metadata:
      labels:
        app: song-recommender-app
    spec:
      containers:
      - name: song-recommender-app
        image: gabrielurbanin/song-recommender-app:v1.2
        volumeMounts:
        - name: song-recommender-app-volume
          mountPath: /app/model
      volumes:
      - name: song-recommender-app-volume
        persistentVolumeClaim:
          claimName: project2-pvc
  backoffLimit: 4