apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc
  namespace: gabrieltavares
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class-gabrieltavares
  selector:
    matchLabels:
      namespace: gabrieltavares